import Head from 'next/head'
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Haji App | Bayar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head>
      <script src="/script.js"></script>
      <main>
        <body>
        <div className="px-8 py-12">
        <img src="/bayar.png" className='mx-auto' alt="" />
        <img src="/info.png" alt="tenangnya text" className="scale-140 ml-3 mt-12" />
        <img src="/cheat.png" alt="tenangnya text" className="scale-140 mt-5" />
        <p className="text-black text-l ml-2 mt-3">Silahkan Selesaikan Pembayaran</p>
        <p className="text-black text-l ml-2">Anda Dalam:    
        <div className="font-bold">
                <span id='hours' className='text-[#CB3A31]'> 03</span>
                <span className='text-[#CB3A31]'> : </span>
                <span id='minutes' className='text-[#CB3A31]'>00</span>
                <span className='text-[#CB3A31]'> : </span>
                <span id='second' className='text-[#CB3A31]'> 00</span>
                <span id='session' className='text-[#CB3A31]'> AM</span>
        </div>
            </p>
        <img src="/qris.png" alt="tenangnya text" className="scale-140 mt-5" />
        <div className="mx-auto px-20">
        <Link href="/" class="mt-2 inline-flex  items-center px-6 py-4 text-sm font-bold object-center text-center text-white bg-[#CB3A31] rounded-lg">Simpan Kode QR</Link>
        </div>
        <img src="/alert.png" alt="tenangnya text" className="scale-140 mt-5" />
        </div>
        <footer>
          <div class="text-center p-6 mt-10 bg-[#404040]">
            <span className='text-white'>© 2021 Copyright: </span>
            <a class="text-white" href="https://tailwind-elements.com/">LontarLab</a>
          </div>
          </footer>   
        </body>
      </main>
    </div>
  );
}
