import Head from 'next/head'
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Haji App | Isi Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head>
      <main>
        <body>
        <div className="px-8 py-12">
           <img src="/isidata.png" className='mx-auto' alt="" />
           <h2 className="font-bold text-l mt-12">Paket yang dipilih :</h2>   
           <a href="#" className="flex items-center bg-white border border-gray-200 rounded-lg shadow-lg mt-3 flex-row max-w-xl dark:border-gray-700 dark:bg-gray-800">
                <img src="/petugas.png" className='ml- scale-130 object-cover ml-3' alt="" />
                <div className="flex flex-col justify-between p-1 leading-normal">
                    <h5 className="mb-1 text-l font-bold tracking-tight text-gray-900 dark:text-white">Internet RoaMax
                    Petugas Haji</h5>
                    <p className="font-bold text-3xl text-[#CB3A31]">15 GB | <span className='font-medium text-xl text-[#CB3A31]'> 50 Hari</span></p>
                </div>
            </a>
            <h2 className="font-bold text-l mt-6">Isi data anda!</h2>   
                <a href="#" className="flex items-center bg-white border border-gray-200 rounded-lg shadow-lg mt-3 flex-row max-w-xl dark:border-gray-700 dark:bg-gray-800">
                <div class="mb-6">
                <label class="block text-gray-700 font-medium mb-2 mt-3 ml-5" for="username">
                  Nomor yang diisi <span className='text-[#CB3A31]'>*</span>
                </label>
                <input  placeholder="+62"  class="shadow appearance-none border rounded py-1 ml-5 px-5" id="username" type="text"/>
                <label class="block text-gray-700 font-medium mb-2 mt-3 ml-5" for="username">
                  Nama <span className='text-[#CB3A31]'>*</span>
                </label>
                <input  placeholder="Masukan nama anda"  class="shadow appearance-none border rounded py-1 ml-5 px-5" id="username" type="text"/>
                <label class="block text-gray-700 font-medium mb-2 mt-3 ml-5" for="username">
                  Upload dokumen pendukung <span className='text-[#CB3A31]'>*</span>
                </label>
                <div div class="flex items-center justify-center w-full ml-3 px-2 mt-4">
                  <label for="dropzone-file" class="flex flex-col items-center justify-center w-full h-44 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600">
                      <div class="flex flex-col items-center justify-center pt-5 pb-6">
                          <svg aria-hidden="true" class="w-10 h-10 mb-3 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"></path></svg>
                          <p class="mb-2 text-sm text-gray-500 dark:text-gray-400">Click to upload</p>     
                          </div>
                      <input id="dropzone-file" type="file" class="hidden" />
                  </label>
              </div> 
              
              </div>
            </a>
            <a href="#" className="flex items-center mb-2 bg-white border border-gray-200 rounded-lg shadow-lg mt-3 dark:border-gray-700 dark:bg-gray-800">
                <div className="flex flex-col justify-between p-1 leading-normal">
                    <h5 className="mb-1 text-l mt-2 ml-3 font-medium tracking-tight text-gray-900 dark:text-white">Total Harga</h5>
                    <h5 className="mb-1 text-2xl mt-2 ml-3 font-bold tracking-tight text-gray-900 dark:text-white">Rp. 750.000<Link href="/konfirmasi" className='text-medium ml-12 inline-flex items-center px-6 py-3 text-sm font-medium text-center text-white bg-[#CB3A31] rounded-lg mb-2'>Lanjutkan</Link></h5>
                </div>
            </a>
            <h2 className="font-bold text-l text-center text-[#CB3A31]">Harap mengisi form dibawah ini</h2>  
            <a href="#" className="flex items-center bg-white border border-gray-200 rounded-lg shadow-lg mt-3 flex-row max-w-xl dark:border-gray-700 dark:bg-gray-800">
                <div class="mb-6">
                <label class="block text-gray-700 font-medium mb-2 mt-3 ml-5" for="username">
                  Nomor Whatsapp <span className='text-[#CB3A31]'></span>
                </label>
                <input  placeholder="+62"  class="shadow appearance-none border rounded py-1 ml-5 px-5" id="username" type="text"/>
                <label class="block text-gray-700 font-medium mb-2 mt-3 ml-5" for="username">
                  Email <span className='text-[#CB3A31]'></span>
                </label>
                <input  placeholder="Masukan email anda"  class="shadow appearance-none border rounded py-1 ml-5 px-5" id="username" type="text"/>
              </div>
            </a> 
          </div>
          
          <footer>
          <div class="text-center p-6 mt-10 bg-[#404040]">
            <span className='text-white'>© 2021 Copyright: </span>
            <a class="text-white" href="https://tailwind-elements.com/">LontarLab</a>
          </div>
          </footer>
        </body>
      </main>
    </div>
  );
}
